### PR TITLE
fixing exports in package.json

### PR DESCRIPTION
**Pull request by fahad86**

### CODE REVIEW

**Comment by fatso83** [comment]
Hi, this has no real description, so I do not what your issue is? AFAIK the exports work fine. 

I actually have quite [decent integration test coverage of this project](https://github.com/fatso83/retry-dynamic-import/tree/main/test-builds), by actually testing the resulting builds:
- typescript with default module resolution
- typescript with nodenext module resolution
- typescript with default module resolution that pulls in react

Does your project fall into another category? If so, maybe clone this repo and copy one of the test folders mentioned. It should be quite quick and painless to create a runnable example demonstrating the issue, when using those as template.

**Comment by fatso83** [comment]
I got no response to what this is supposed to be fixing, and I have no issues open, so closing.

**Comment by fatso83** [comment]
After finding issue #6, I suspect you might have hit this snag. Once I knew how to reproduce, I figured out that a couple of issues had appeared with 2.0.4 and 2.0.5. Fixed both of these now.

Could you see if it works for you?

**Comment by fahad86** [comment]
hey @fatso83, sorry for the late response (got a but busy this week and forgot to respond). I've upgraded to 2.1.1 and I can confirm that the issue that I was facing before is now resolved.. Glad you've figured out hte problem..
Thanks for the great work !! 👍🏼

**Pull request closed without merging**
